### ISSUE TITLE
vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead

### ISSUE THREAD

**Issue by Allaman** [David-Kunz/markid#2]
Hello,

thanks for this plugin. I am running Neovim HEAD and got this warning. I am not sure if `vim.api.nvim_set_hl ` is available in Neovim 0.7 but maybe an if checking the Neovim version is appropriate?
<img width="1949" alt="image" src="https://user-images.githubusercontent.com/12184268/189534237-644e7b67-d76c-40ab-8cf0-49f220595f30.png">

**Comment by David-Kunz** [comment]
Hi @Allaman ,

Thanks a lot for the hint!

There's also [this line](https://github.com/nvim-treesitter/nvim-treesitter/blob/965a74f76a2999b81fe3a543fb5e53bf6c84b8b7/lua/nvim-treesitter/highlight.lua#L123) in nvim-treesitter.

I'll fix that!

**Comment by David-Kunz** [comment]
The issue is fixed, thanks again for reporting!
