### ISSUE TITLE
Support for Vue file

### ISSUE THREAD

**Issue by tuanha168** [David-Kunz/markid#7]
Hi, can you add support for `script block` inside a `.vue` file?
I see that vue is using injection `javascript` and `typescript` in `script block` and tried to using `tree sitter query` but can't get it to work. (I'm very new to this)
I really love this plugin and want to use it in my vue project too.
```
(
  (script_element
    (start_tag
      (attribute
        (attribute_name) @_lang
        (quoted_attribute_value (attribute_value) @_ts)))
    (raw_text) @typescript)
  (#eq? @_lang "lang")
  (#eq? @_ts "ts")
)
```

**Comment by David-Kunz** [comment]
Hi @tuanha168 ,

Thanks for the positive feedback! I'm not yet sure if I can get this to work because `nvim-treesitter` is in control of running my extension (which is independent of the outer embedding), but I'll have a look!

Best regards,
David

**Comment by David-Kunz** [comment]
Hi @tuanha168 ,

I'm using `require'nvim-treesitter'.define_modules`. The corresponding `attach` function would be called with language `vue` where the default query cannot be parsed. I would've expected it to be called with `JavaScript`/`TypeScript` for the inner code.

I'll investigate a bit further but I'm afraid it cannot be done.

Thanks and best regards,
David
